# Generated by Django 5.0.6 on 2024-06-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=10, unique=True)),
                ('plan', models.CharField(choices=[('A', 'PlanA'), ('B', 'PlanB'), ('C', 'PlanC')], max_length=1)),
                ('access_roles', models.CharField(choices=[('L', 'Loader'), ('P', 'Planner'), ('H', 'Leadership')], max_length=1)),
                ('standard_container_type', models.CharField(choices=[('G', 'General 20 ft container')], max_length=1)),
                ('standard_source', models.CharField(max_length=100)),
                ('standard_destination', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('container_name', models.CharField(max_length=50)),
                ('container_volume', models.FloatField()),
                ('container_length', models.FloatField()),
                ('container_width', models.FloatField()),
                ('container_height', models.FloatField()),
                ('payload_capacity', models.FloatField()),
                ('container_type', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=100)),
                ('volume_capacity', models.FloatField()),
                ('seperator_pallet', models.BooleanField(default=False)),
                ('door_opening_width', models.FloatField()),
                ('door_opening_length', models.FloatField()),
                ('cubic_capacity', models.FloatField()),
                ('tare_weight', models.FloatField()),
                ('max_gross_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('sku_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('sku_name', models.CharField(max_length=50, unique=True)),
                ('sku_description', models.TextField()),
                ('sku_type', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('gross_weight', models.FloatField()),
                ('net_weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('product_hierarchy', models.TextField()),
                ('incompatibility', models.CharField(max_length=100)),
                ('max_stack_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('product_hierarchy', models.CharField(max_length=100)),
                ('source_location', models.CharField(max_length=100)),
                ('shipping_point', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('planned_start_date', models.DateField()),
                ('planned_delivery_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.company')),
                ('container', models.ManyToManyField(related_name='orders', to='home.container')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sku')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='skus',
            field=models.ManyToManyField(related_name='orders', through='home.OrderSKU', to='home.sku'),
        ),
        migrations.AddField(
            model_name='company',
            name='SKUs',
            field=models.ManyToManyField(related_name='companies_as_SKU', to='home.sku'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(default='000000', max_length=10, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('OptipackTeam', 'OptipackTeam'), ('Company_SuperAdmin', 'Company_SuperAdmin'), ('Company_Admin', 'Company_Admin'), ('Company_loader', 'Company_loader'), ('Company_planner', 'Company_planner')], max_length=20)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_status', models.CharField(choices=[('Exp', 'expired'), ('Active', 'Active'), ('Dormant', 'Dormant')], max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='home.company')),
            ],
            options={
                'unique_together': {('user_id', 'email_id')},
            },
        ),
        migrations.CreateModel(
            name='LoadPlan',
            fields=[
                ('plan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('utilization', models.FloatField()),
                ('volume_untilized', models.FloatField()),
                ('volume_available', models.FloatField()),
                ('load_details', models.TextField()),
                ('unplanned_load', models.TextField()),
                ('image_top', models.ImageField(upload_to='top_images')),
                ('image_bottom', models.ImageField(upload_to='bottom_images')),
                ('image_left', models.ImageField(upload_to='left_images')),
                ('image_right', models.ImageField(upload_to='right_images')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_plan', to='home.order')),
                ('orderSKU', models.ManyToManyField(related_name='load_plan', to='home.ordersku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_plan', to='home.users')),
            ],
        ),
    ]
