# Generated by Django 5.0.6 on 2024-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='standard_container_type',
            field=models.CharField(choices=[('Gen20F', 'General 20 ft container'), ('Gen40F', 'General 40 ft container'), ('High40F', 'HighCube 40 ft container')], max_length=20),
        ),
    ]
