# Generated by Django 5.0.6 on 2024-07-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_company_standard_container_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='standard_destination',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='standard_source',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
